[colors]
ansi = [
    '#4b565c',
    '#e67e80',
    '#a7c080',
    '#dbbc7f',
    '#7fbbb3',
    '#d699b6',
    '#83c092',
    '#d3c6aa'
]
background = '#2d353b'
brights = [
    '#4f585e',
    '#e67e80',
    '#a7c080',
    '#dbbc7f',
    '#7fbbb3',
    '#d699b6',
    '#83c092',
    '#d3c6aa'
]
cursor_bg ='#d3c6aa'
cursor_border = '#d3c6aa'
cursor_fg = '#2d353b'
foreground = '#d3c6aa'

[metadata]
name = "everforest-dark"
author = "sainnhe"
origin_url = "https://github.com/sainnhe/everforest"
